source 'https://rubygems.org'

gem 'rails', '3.2.8'

# We're using Carrierwave (https://github.com/jnicklas/carrierwave/)
gem 'carrierwave'
gem "mini_magick"

gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
